definitions:
  handlers.UploadFileResponse:
    properties:
      message:
        type: string
      uploadpath:
        type: string
    type: object
  handlers.loginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  handlers.loginResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      token:
        type: string
    type: object
  handlers.successResponse:
    properties:
      message:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      details:
        description: 错误详情（可选字段）
        type: string
      error_code:
        description: 错误码
        type: integer
      error_msg:
        description: 错误具体信息
        type: string
    type: object
  models.Permission:
    properties:
      description:
        description: 权限描述
        type: string
      id:
        type: integer
      name:
        description: 权限名称
        type: string
      roles:
        description: 权限属于的角色（多对多关系）
        items:
          $ref: '#/definitions/models.Role'
        type: array
    type: object
  models.Role:
    properties:
      description:
        description: 角色描述
        type: string
      id:
        type: integer
      name:
        description: 角色名称
        type: string
      permissions:
        description: 角色拥有的权限（多对多关系）
        items:
          $ref: '#/definitions/models.Permission'
        type: array
      userRoles:
        description: 用户角色关联
        items:
          $ref: '#/definitions/models.UserRole'
        type: array
    type: object
  models.User:
    properties:
      email:
        description: 用户邮箱（可选）
        type: string
      id:
        type: integer
      password:
        description: 加密后的密码
        type: string
      userRoles:
        description: 用户角色关联
        items:
          $ref: '#/definitions/models.UserRole'
        type: array
      username:
        description: 用户名（唯一）
        type: string
    type: object
  models.UserRole:
    properties:
      role:
        $ref: '#/definitions/models.Role'
      roleID:
        description: 角色ID
        type: integer
      user:
        $ref: '#/definitions/models.User'
      userID:
        description: 用户ID
        type: integer
    type: object
info:
  contact: {}
paths:
  /authorize/login:
    post:
      consumes:
      - application/json
      description: 用户登录并获取令牌
      parameters:
      - description: 登录信息
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/handlers.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 用户登录
      tags:
      - 用户
  /authorize/logout:
    post:
      description: 注销当前用户
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.successResponse'
      summary: 用户注销
      tags:
      - 用户
  /authorize/register:
    post:
      consumes:
      - application/json
      description: 注册新用户
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.successResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 用户注册
      tags:
      - 用户
  /ping:
    get:
      description: Responds with a "pong" message to indicate the service is running.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: PingHandler endpoint
      tags:
      - Health
  /upload:
    put:
      consumes:
      - multipart/form-data
      description: Uploads a file to the server using the PUT method and simulates
        object storage
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Base64 encoded MD5 hash of the file
        in: header
        name: Content-MD5
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.UploadFileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Upload a file to the server (simulating object storage)
      tags:
      - file
  /users/{id}:
    get:
      description: 根据用户ID获取用户信息
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 获取用户信息
      tags:
      - 用户
    put:
      consumes:
      - application/json
      description: 修改当前用户的信息
      parameters:
      - description: 用户信息
        in: body
        name: userInfo
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.successResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 修改用户信息
      tags:
      - 用户
swagger: "2.0"
