name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.24' ]

    steps:
      # 1. 拉取代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. 设置 Go 环境
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      # 3. 检查 `go.mod` 和 `go.sum`
      - name: Verify dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
      
      # 4. 下载依赖
      - name: Download Dependencies
        run: go mod download

      # 5. 代码格式检查（可选）
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m
      
      # 6. 构建项目
      - name: Build Application
        run: go build -v ./...
      
      # 7. 运行单元测试
      - name: Run Tests
        run: go test -v ./...
